#!/usr/bin/bash 

function execute_scripts_in_directory {
    local DIR="$1"
    if [ -d "$DIR" ]; then
        echo "Installiere Skripte in: $DIR"

        # Alle ausführbaren Dateien im Verzeichnis finden und ausführen
        for SCRIPT in "$DIR"/*; do
            if [ -f "$SCRIPT" ] && [ -x "$SCRIPT" ]; then
                echo "Starte: $SCRIPT"
                "$SCRIPT"  # Skript ausführen
            else
                echo "Überspringe (nicht ausführbar): $SCRIPT"
            fi
        done
    else
        echo "Verzeichnis existiert nicht: $DIR"
    fi
}


function execute_all_scripts {
    local RUNS_DIR="runs"

    for DIR in "RUNS_DIR"/*; do
        execute_script_in_directory "$DIR"
    done
}

function execute_scripts_in_selected_directory {
    local RUNS_DIR="runs"
    local SELECTION="$1"

    local TARGET_DIR="$RUNS_DIR/$SELECTION"
    execute_scripts_in_directory "$TARGET_DIR"
}

function copy_dotfiles {
    echo "Verschiebe Dotfiles und Konfigurationsdateien..."
    local ENV_DIR="env"
    find "$ENV_DIR" -type f | while read -r file; do
    # Relativen Pfad zum ENV_DIR ermitteln
    rel_path="${file#"$ENV_DIR"/}"
    target="$HOME/$rel_path"

    # Verzeichnisstruktur im Zielverzeichnis erstellen
    mkdir -p "$(dirname "$target")"

    # Datei nur verschieben, wenn sie nicht bereits existiert
    if [[ ! -e "$target" ]]; then
        echo "Verschiebe '$file' nach '$target'"
        cp "$file" "$target"
    else
        echo "Die Datei '$target' existiert bereits. Überspringe das Verschieben."
    fi
done
}


function main {
    if [ -n "$1" ]; then 
        execute_scripts_in_selected_directory "$1"
    else 
        execute_all_scripts
    fi

    copy_dotfiles

}

main "$1"
