#!/usr/bin/bash

# Verzeichnisse definieren
RUNS_DIR="runs"
ENV_DIR="env"

# Alle Skripte im 'runs' Verzeichnis ausführen
echo "Führe Skripte in '$RUNS_DIR' aus..."

for run_script in "$RUNS_DIR"/*; do
    # Sicherstellen, dass es eine Datei ist und sie ausführbar ist
    if [[ -f "$run_script" && -x "$run_script" ]]; then
        echo "Führe '$run_script' aus..."
        bash "$run_script"
    else
        echo "Die Datei '$run_script' ist keine ausführbare Datei oder nicht vorhanden."
   fi
done

cp -r bin/ ~/

# Dotfiles und Konfigurationsdateien verschieben
echo "Verschiebe Dotfiles und Konfigurationsdateien..."

find "$ENV_DIR" -type f | while read -r file; do
    # Relativen Pfad zum ENV_DIR ermitteln
    rel_path="${file#"$ENV_DIR"/}"
    target="$HOME/$rel_path"

    # Verzeichnisstruktur im Zielverzeichnis erstellen
    mkdir -p "$(dirname "$target")"

    # Datei nur verschieben, wenn sie nicht bereits existiert
    if [[ ! -e "$target" ]]; then
        echo "Verschiebe '$file' nach '$target'"
        cp "$file" "$target"
    else
        echo "Die Datei '$target' existiert bereits. Überspringe das Verschieben."
    fi
done


echo "Alle Aufgaben abgeschlossen."

