#!/usr/bin/bash

sudo apt-get install python3-dev python3-virtualenv python3-examples python3-tk \
python3-pip python3-numpy python3-matplotlib python3-cffi python3-scipy ipython3 \
python3-httplib2 python3-netifaces python3-pandas python3-bs4 python3-requests \
python3-six python3-werkzeug python3-psycopg2 python3-reportlab python3-setuptools \
python3-pil python3-lxml python3-yaml python3-pyqt5 python3-pyqt5.qtsvg python3-pyqt5.qtwebkit \
qttools5-dev-tools qttools5-dev qtcreator

pip install --upgrade pwntools PyQt6 PySide6 PySide2

